//
//  Color+CSS.swift
//  Crayon
//
//  Created by David Walter on 07.07.24.
//

#if canImport(SwiftUI)
import SwiftUI

@available(iOS 13, macOS 10.15, watchOS 6, tvOS 13, *)
extension Color {
    public static var css: CSS.Type {
        CSS.self
    }
    
    public struct CSS {
          public static let aliceblue = Color(hex: "#f0f8ff")
          public static let antiquewhite = Color(hex: "#faebd7")
          public static let aqua = Color(hex: "#00ffff")
          public static let aquamarine = Color(hex: "#7fffd4")
          public static let azure = Color(hex: "#f0ffff")
          public static let beige = Color(hex: "#f5f5dc")
          public static let bisque = Color(hex: "#ffe4c4")
          public static let black = Color(hex: "#000000")
          public static let blanchedalmond = Color(hex: "#ffebcd")
          public static let blue = Color(hex: "#0000ff")
          public static let blueviolet = Color(hex: "#8a2be2")
          public static let brown = Color(hex: "#a52a2a")
          public static let burlywood = Color(hex: "#deb887")
          public static let cadetblue = Color(hex: "#5f9ea0")
          public static let chartreuse = Color(hex: "#7fff00")
          public static let chocolate = Color(hex: "#d2691e")
          public static let coral = Color(hex: "#ff7f50")
          public static let cornflowerblue = Color(hex: "#6495ed")
          public static let cornsilk = Color(hex: "#fff8dc")
          public static let crimson = Color(hex: "#dc143c")
          public static let cyan = Color(hex: "#00ffff")
          public static let darkBblue = Color(hex: "#00008b")
          public static let darkCyan = Color(hex: "#008b8b")
          public static let darkGoldenrod = Color(hex: "#b8860b")
          public static let darkGray = Color(hex: "#a9a9a9")
          public static let darkGreen = Color(hex: "#006400")
          public static let darkKhaki = Color(hex: "#bdb76b")
          public static let darkMagenta = Color(hex: "#8b008b")
          public static let darkOliveGreen = Color(hex: "#556b2f")
          public static let darkOrange = Color(hex: "#ff8c00")
          public static let darkOrchid = Color(hex: "#9932cc")
          public static let darkRed = Color(hex: "#8b0000")
          public static let darkSalmon = Color(hex: "#e9967a")
          public static let darkSeagreen = Color(hex: "#8fbc8f")
          public static let darkSlateBlue = Color(hex: "#483d8b")
          public static let darkSlateGray = Color(hex: "#2f4f4f")
          public static let darkTurquoise = Color(hex: "#00ced1")
          public static let darkViolet = Color(hex: "#9400d3")
          public static let deepPink = Color(hex: "#ff1493")
          public static let deepSkyBlue = Color(hex: "#00bfff")
          public static let dimGray = Color(hex: "#696969")
          public static let dodgerBlue = Color(hex: "#1e90ff")
          public static let fireBrick = Color(hex: "#b22222")
          public static let floralWhite = Color(hex: "#fffaf0")
          public static let forestGreen = Color(hex: "#228b22")
          public static let fuchsia = Color(hex: "#ff00ff")
          public static let gainsboro = Color(hex: "#dcdcdc")
          public static let ghostWhite = Color(hex: "#f8f8ff")
          public static let goldenrod = Color(hex: "#daa520")
          public static let gold = Color(hex: "#ffd700")
          public static let gray = Color(hex: "#808080")
          public static let green = Color(hex: "#008000")
          public static let greenYellow = Color(hex: "#adff2f")
          public static let grey = Color(hex: "#808080")
          public static let honeydew = Color(hex: "#f0fff0")
          public static let hotpink = Color(hex: "#ff69b4")
          public static let indianred = Color(hex: "#cd5c5c")
          public static let indigo = Color(hex: "#4b0082")
          public static let ivory = Color(hex: "#fffff0")
          public static let khaki = Color(hex: "#f0e68c")
          public static let lavenderblush = Color(hex: "#fff0f5")
          public static let lavender = Color(hex: "#e6e6fa")
          public static let lawngreen = Color(hex: "#7cfc00")
          public static let lemonchiffon = Color(hex: "#fffacd")
          public static let lightBlue = Color(hex: "#add8e6")
          public static let lightCoral = Color(hex: "#f08080")
          public static let lightCyan = Color(hex: "#e0ffff")
          public static let lightGoldenrodyellow = Color(hex: "#fafad2")
          public static let lightGray = Color(hex: "#d3d3d3")
          public static let lightGreen = Color(hex: "#90ee90")
          public static let lightGrey = Color(hex: "#d3d3d3")
          public static let lightPink = Color(hex: "#ffb6c1")
          public static let lightSalmon = Color(hex: "#ffa07a")
          public static let lightSeagreen = Color(hex: "#20b2aa")
          public static let lightSkyblue = Color(hex: "#87cefa")
          public static let lightSlateGray = Color(hex: "#778899")
          public static let lightSlateGrey = Color(hex: "#778899")
          public static let lightSteelBlue = Color(hex: "#b0c4de")
          public static let lightYellow = Color(hex: "#ffffe0")
          public static let lime = Color(hex: "#00ff00")
          public static let limegreen = Color(hex: "#32cd32")
          public static let linen = Color(hex: "#faf0e6")
          public static let magenta = Color(hex: "#ff00ff")
          public static let maroon = Color(hex: "#800000")
          public static let mediumAquamarine = Color(hex: "#66cdaa")
          public static let mediumBlue = Color(hex: "#0000cd")
          public static let mediumOrchid = Color(hex: "#ba55d3")
          public static let mediumPurple = Color(hex: "#9370db")
          public static let mediumSeagreen = Color(hex: "#3cb371")
          public static let mediumSlateBlue = Color(hex: "#7b68ee")
          public static let mediumSpringGreen = Color(hex: "#00fa9a")
          public static let mediumTurquoise = Color(hex: "#48d1cc")
          public static let mediumVioletRed = Color(hex: "#c71585")
          public static let midnightBlue = Color(hex: "#191970")
          public static let mintcream = Color(hex: "#f5fffa")
          public static let mistyrose = Color(hex: "#ffe4e1")
          public static let moccasin = Color(hex: "#ffe4b5")
          public static let navajowhite = Color(hex: "#ffdead")
          public static let navy = Color(hex: "#000080")
          public static let oldlace = Color(hex: "#fdf5e6")
          public static let olive = Color(hex: "#808000")
          public static let olivedrab = Color(hex: "#6b8e23")
          public static let orange = Color(hex: "#ffa500")
          public static let orangered = Color(hex: "#ff4500")
          public static let orchid = Color(hex: "#da70d6")
          public static let paleGoldenrod = Color(hex: "#eee8aa")
          public static let paleGreen = Color(hex: "#98fb98")
          public static let paleTurquoise = Color(hex: "#afeeee")
          public static let paleVioletRed = Color(hex: "#db7093")
          public static let papayaWhip = Color(hex: "#ffefd5")
          public static let peachPuff = Color(hex: "#ffdab9")
          public static let peru = Color(hex: "#cd853f")
          public static let pink = Color(hex: "#ffc0cb")
          public static let plum = Color(hex: "#dda0dd")
          public static let powderBlue = Color(hex: "#b0e0e6")
          public static let purple = Color(hex: "#800080")
          public static let rebeccapurple = Color(hex: "#663399")
          public static let red = Color(hex: "#ff0000")
          public static let rosyBrown = Color(hex: "#bc8f8f")
          public static let royalBlue = Color(hex: "#4169e1")
          public static let saddleBrown = Color(hex: "#8b4513")
          public static let salmon = Color(hex: "#fa8072")
          public static let sandyBrown = Color(hex: "#f4a460")
          public static let seagreen = Color(hex: "#2e8b57")
          public static let seashell = Color(hex: "#fff5ee")
          public static let sienna = Color(hex: "#a0522d")
          public static let silver = Color(hex: "#c0c0c0")
          public static let skyBlue = Color(hex: "#87ceeb")
          public static let slateBlue = Color(hex: "#6a5acd")
          public static let slateGray = Color(hex: "#708090")
          public static let snow = Color(hex: "#fffafa")
          public static let springGreen = Color(hex: "#00ff7f")
          public static let steelBlue = Color(hex: "#4682b4")
          public static let tan = Color(hex: "#d2b48c")
          public static let teal = Color(hex: "#008080")
          public static let thistle = Color(hex: "#d8bfd8")
          public static let tomato = Color(hex: "#ff6347")
          public static let turquoise = Color(hex: "#40e0d0")
          public static let violet = Color(hex: "#ee82ee")
          public static let wheat = Color(hex: "#f5deb3")
          public static let white = Color(hex: "#ffffff")
          public static let whiteSmoke = Color(hex: "#f5f5f5")
          public static let yellow = Color(hex: "#ffff00")
          public static let yellowGreen = Color(hex: "#9acd32")
    }
}
#endif
