//
//  NSColor+CSS.swift
//  Crayon
//
//  Created by David Walter on 07.07.24.
//

#if canImport(AppKit) && os(macOS)
import AppKit

extension NSColor {
    public static var css: CSS.Type {
        CSS.self
    }
    
    public struct CSS {
          public static let aliceblue = NSColor(hex: "#f0f8ff")
          public static let antiquewhite = NSColor(hex: "#faebd7")
          public static let aqua = NSColor(hex: "#00ffff")
          public static let aquamarine = NSColor(hex: "#7fffd4")
          public static let azure = NSColor(hex: "#f0ffff")
          public static let beige = NSColor(hex: "#f5f5dc")
          public static let bisque = NSColor(hex: "#ffe4c4")
          public static let black = NSColor(hex: "#000000")
          public static let blanchedalmond = NSColor(hex: "#ffebcd")
          public static let blue = NSColor(hex: "#0000ff")
          public static let blueviolet = NSColor(hex: "#8a2be2")
          public static let brown = NSColor(hex: "#a52a2a")
          public static let burlywood = NSColor(hex: "#deb887")
          public static let cadetblue = NSColor(hex: "#5f9ea0")
          public static let chartreuse = NSColor(hex: "#7fff00")
          public static let chocolate = NSColor(hex: "#d2691e")
          public static let coral = NSColor(hex: "#ff7f50")
          public static let cornflowerblue = NSColor(hex: "#6495ed")
          public static let cornsilk = NSColor(hex: "#fff8dc")
          public static let crimson = NSColor(hex: "#dc143c")
          public static let cyan = NSColor(hex: "#00ffff")
          public static let darkblue = NSColor(hex: "#00008b")
          public static let darkcyan = NSColor(hex: "#008b8b")
          public static let darkgoldenrod = NSColor(hex: "#b8860b")
          public static let darkgray = NSColor(hex: "#a9a9a9")
          public static let darkgreen = NSColor(hex: "#006400")
          public static let darkgrey = NSColor(hex: "#a9a9a9")
          public static let darkkhaki = NSColor(hex: "#bdb76b")
          public static let darkmagenta = NSColor(hex: "#8b008b")
          public static let darkolivegreen = NSColor(hex: "#556b2f")
          public static let darkorange = NSColor(hex: "#ff8c00")
          public static let darkorchid = NSColor(hex: "#9932cc")
          public static let darkred = NSColor(hex: "#8b0000")
          public static let darksalmon = NSColor(hex: "#e9967a")
          public static let darkseagreen = NSColor(hex: "#8fbc8f")
          public static let darkslateblue = NSColor(hex: "#483d8b")
          public static let darkslategray = NSColor(hex: "#2f4f4f")
          public static let darkslategrey = NSColor(hex: "#2f4f4f")
          public static let darkturquoise = NSColor(hex: "#00ced1")
          public static let darkviolet = NSColor(hex: "#9400d3")
          public static let deeppink = NSColor(hex: "#ff1493")
          public static let deepskyblue = NSColor(hex: "#00bfff")
          public static let dimgray = NSColor(hex: "#696969")
          public static let dimgrey = NSColor(hex: "#696969")
          public static let dodgerblue = NSColor(hex: "#1e90ff")
          public static let firebrick = NSColor(hex: "#b22222")
          public static let floralwhite = NSColor(hex: "#fffaf0")
          public static let forestgreen = NSColor(hex: "#228b22")
          public static let fuchsia = NSColor(hex: "#ff00ff")
          public static let gainsboro = NSColor(hex: "#dcdcdc")
          public static let ghostwhite = NSColor(hex: "#f8f8ff")
          public static let goldenrod = NSColor(hex: "#daa520")
          public static let gold = NSColor(hex: "#ffd700")
          public static let gray = NSColor(hex: "#808080")
          public static let green = NSColor(hex: "#008000")
          public static let greenyellow = NSColor(hex: "#adff2f")
          public static let grey = NSColor(hex: "#808080")
          public static let honeydew = NSColor(hex: "#f0fff0")
          public static let hotpink = NSColor(hex: "#ff69b4")
          public static let indianred = NSColor(hex: "#cd5c5c")
          public static let indigo = NSColor(hex: "#4b0082")
          public static let ivory = NSColor(hex: "#fffff0")
          public static let khaki = NSColor(hex: "#f0e68c")
          public static let lavenderblush = NSColor(hex: "#fff0f5")
          public static let lavender = NSColor(hex: "#e6e6fa")
          public static let lawngreen = NSColor(hex: "#7cfc00")
          public static let lemonchiffon = NSColor(hex: "#fffacd")
          public static let lightblue = NSColor(hex: "#add8e6")
          public static let lightcoral = NSColor(hex: "#f08080")
          public static let lightcyan = NSColor(hex: "#e0ffff")
          public static let lightgoldenrodyellow = NSColor(hex: "#fafad2")
          public static let lightgray = NSColor(hex: "#d3d3d3")
          public static let lightgreen = NSColor(hex: "#90ee90")
          public static let lightgrey = NSColor(hex: "#d3d3d3")
          public static let lightpink = NSColor(hex: "#ffb6c1")
          public static let lightsalmon = NSColor(hex: "#ffa07a")
          public static let lightseagreen = NSColor(hex: "#20b2aa")
          public static let lightskyblue = NSColor(hex: "#87cefa")
          public static let lightslategray = NSColor(hex: "#778899")
          public static let lightslategrey = NSColor(hex: "#778899")
          public static let lightsteelblue = NSColor(hex: "#b0c4de")
          public static let lightyellow = NSColor(hex: "#ffffe0")
          public static let lime = NSColor(hex: "#00ff00")
          public static let limegreen = NSColor(hex: "#32cd32")
          public static let linen = NSColor(hex: "#faf0e6")
          public static let magenta = NSColor(hex: "#ff00ff")
          public static let maroon = NSColor(hex: "#800000")
          public static let mediumaquamarine = NSColor(hex: "#66cdaa")
          public static let mediumblue = NSColor(hex: "#0000cd")
          public static let mediumorchid = NSColor(hex: "#ba55d3")
          public static let mediumpurple = NSColor(hex: "#9370db")
          public static let mediumseagreen = NSColor(hex: "#3cb371")
          public static let mediumslateblue = NSColor(hex: "#7b68ee")
          public static let mediumspringgreen = NSColor(hex: "#00fa9a")
          public static let mediumturquoise = NSColor(hex: "#48d1cc")
          public static let mediumvioletred = NSColor(hex: "#c71585")
          public static let midnightblue = NSColor(hex: "#191970")
          public static let mintcream = NSColor(hex: "#f5fffa")
          public static let mistyrose = NSColor(hex: "#ffe4e1")
          public static let moccasin = NSColor(hex: "#ffe4b5")
          public static let navajowhite = NSColor(hex: "#ffdead")
          public static let navy = NSColor(hex: "#000080")
          public static let oldlace = NSColor(hex: "#fdf5e6")
          public static let olive = NSColor(hex: "#808000")
          public static let olivedrab = NSColor(hex: "#6b8e23")
          public static let orange = NSColor(hex: "#ffa500")
          public static let orangered = NSColor(hex: "#ff4500")
          public static let orchid = NSColor(hex: "#da70d6")
          public static let palegoldenrod = NSColor(hex: "#eee8aa")
          public static let palegreen = NSColor(hex: "#98fb98")
          public static let paleturquoise = NSColor(hex: "#afeeee")
          public static let palevioletred = NSColor(hex: "#db7093")
          public static let papayawhip = NSColor(hex: "#ffefd5")
          public static let peachpuff = NSColor(hex: "#ffdab9")
          public static let peru = NSColor(hex: "#cd853f")
          public static let pink = NSColor(hex: "#ffc0cb")
          public static let plum = NSColor(hex: "#dda0dd")
          public static let powderblue = NSColor(hex: "#b0e0e6")
          public static let purple = NSColor(hex: "#800080")
          public static let rebeccapurple = NSColor(hex: "#663399")
          public static let red = NSColor(hex: "#ff0000")
          public static let rosybrown = NSColor(hex: "#bc8f8f")
          public static let royalblue = NSColor(hex: "#4169e1")
          public static let saddlebrown = NSColor(hex: "#8b4513")
          public static let salmon = NSColor(hex: "#fa8072")
          public static let sandybrown = NSColor(hex: "#f4a460")
          public static let seagreen = NSColor(hex: "#2e8b57")
          public static let seashell = NSColor(hex: "#fff5ee")
          public static let sienna = NSColor(hex: "#a0522d")
          public static let silver = NSColor(hex: "#c0c0c0")
          public static let skyblue = NSColor(hex: "#87ceeb")
          public static let slateblue = NSColor(hex: "#6a5acd")
          public static let slategray = NSColor(hex: "#708090")
          public static let slategrey = NSColor(hex: "#708090")
          public static let snow = NSColor(hex: "#fffafa")
          public static let springgreen = NSColor(hex: "#00ff7f")
          public static let steelblue = NSColor(hex: "#4682b4")
          public static let tan = NSColor(hex: "#d2b48c")
          public static let teal = NSColor(hex: "#008080")
          public static let thistle = NSColor(hex: "#d8bfd8")
          public static let tomato = NSColor(hex: "#ff6347")
          public static let turquoise = NSColor(hex: "#40e0d0")
          public static let violet = NSColor(hex: "#ee82ee")
          public static let wheat = NSColor(hex: "#f5deb3")
          public static let white = NSColor(hex: "#ffffff")
          public static let whitesmoke = NSColor(hex: "#f5f5f5")
          public static let yellow = NSColor(hex: "#ffff00")
          public static let yellowgreen = NSColor(hex: "#9acd32")
    }
}
#endif
