//
//  UIColor+CSS.swift
//  Crayon
//
//  Created by David Walter on 07.07.24.
//

#if canImport(UIKit)
import UIKit

extension UIColor {
    public static var css: CSS.Type {
        CSS.self
    }
    
    public struct CSS {
          public static let aliceblue = UIColor(hex: "#f0f8ff")
          public static let antiquewhite = UIColor(hex: "#faebd7")
          public static let aqua = UIColor(hex: "#00ffff")
          public static let aquamarine = UIColor(hex: "#7fffd4")
          public static let azure = UIColor(hex: "#f0ffff")
          public static let beige = UIColor(hex: "#f5f5dc")
          public static let bisque = UIColor(hex: "#ffe4c4")
          public static let black = UIColor(hex: "#000000")
          public static let blanchedalmond = UIColor(hex: "#ffebcd")
          public static let blue = UIColor(hex: "#0000ff")
          public static let blueviolet = UIColor(hex: "#8a2be2")
          public static let brown = UIColor(hex: "#a52a2a")
          public static let burlywood = UIColor(hex: "#deb887")
          public static let cadetblue = UIColor(hex: "#5f9ea0")
          public static let chartreuse = UIColor(hex: "#7fff00")
          public static let chocolate = UIColor(hex: "#d2691e")
          public static let coral = UIColor(hex: "#ff7f50")
          public static let cornflowerblue = UIColor(hex: "#6495ed")
          public static let cornsilk = UIColor(hex: "#fff8dc")
          public static let crimson = UIColor(hex: "#dc143c")
          public static let cyan = UIColor(hex: "#00ffff")
          public static let darkblue = UIColor(hex: "#00008b")
          public static let darkcyan = UIColor(hex: "#008b8b")
          public static let darkgoldenrod = UIColor(hex: "#b8860b")
          public static let darkgray = UIColor(hex: "#a9a9a9")
          public static let darkgreen = UIColor(hex: "#006400")
          public static let darkgrey = UIColor(hex: "#a9a9a9")
          public static let darkkhaki = UIColor(hex: "#bdb76b")
          public static let darkmagenta = UIColor(hex: "#8b008b")
          public static let darkolivegreen = UIColor(hex: "#556b2f")
          public static let darkorange = UIColor(hex: "#ff8c00")
          public static let darkorchid = UIColor(hex: "#9932cc")
          public static let darkred = UIColor(hex: "#8b0000")
          public static let darksalmon = UIColor(hex: "#e9967a")
          public static let darkseagreen = UIColor(hex: "#8fbc8f")
          public static let darkslateblue = UIColor(hex: "#483d8b")
          public static let darkslategray = UIColor(hex: "#2f4f4f")
          public static let darkslategrey = UIColor(hex: "#2f4f4f")
          public static let darkturquoise = UIColor(hex: "#00ced1")
          public static let darkviolet = UIColor(hex: "#9400d3")
          public static let deeppink = UIColor(hex: "#ff1493")
          public static let deepskyblue = UIColor(hex: "#00bfff")
          public static let dimgray = UIColor(hex: "#696969")
          public static let dimgrey = UIColor(hex: "#696969")
          public static let dodgerblue = UIColor(hex: "#1e90ff")
          public static let firebrick = UIColor(hex: "#b22222")
          public static let floralwhite = UIColor(hex: "#fffaf0")
          public static let forestgreen = UIColor(hex: "#228b22")
          public static let fuchsia = UIColor(hex: "#ff00ff")
          public static let gainsboro = UIColor(hex: "#dcdcdc")
          public static let ghostwhite = UIColor(hex: "#f8f8ff")
          public static let goldenrod = UIColor(hex: "#daa520")
          public static let gold = UIColor(hex: "#ffd700")
          public static let gray = UIColor(hex: "#808080")
          public static let green = UIColor(hex: "#008000")
          public static let greenyellow = UIColor(hex: "#adff2f")
          public static let grey = UIColor(hex: "#808080")
          public static let honeydew = UIColor(hex: "#f0fff0")
          public static let hotpink = UIColor(hex: "#ff69b4")
          public static let indianred = UIColor(hex: "#cd5c5c")
          public static let indigo = UIColor(hex: "#4b0082")
          public static let ivory = UIColor(hex: "#fffff0")
          public static let khaki = UIColor(hex: "#f0e68c")
          public static let lavenderblush = UIColor(hex: "#fff0f5")
          public static let lavender = UIColor(hex: "#e6e6fa")
          public static let lawngreen = UIColor(hex: "#7cfc00")
          public static let lemonchiffon = UIColor(hex: "#fffacd")
          public static let lightblue = UIColor(hex: "#add8e6")
          public static let lightcoral = UIColor(hex: "#f08080")
          public static let lightcyan = UIColor(hex: "#e0ffff")
          public static let lightgoldenrodyellow = UIColor(hex: "#fafad2")
          public static let lightgray = UIColor(hex: "#d3d3d3")
          public static let lightgreen = UIColor(hex: "#90ee90")
          public static let lightgrey = UIColor(hex: "#d3d3d3")
          public static let lightpink = UIColor(hex: "#ffb6c1")
          public static let lightsalmon = UIColor(hex: "#ffa07a")
          public static let lightseagreen = UIColor(hex: "#20b2aa")
          public static let lightskyblue = UIColor(hex: "#87cefa")
          public static let lightslategray = UIColor(hex: "#778899")
          public static let lightslategrey = UIColor(hex: "#778899")
          public static let lightsteelblue = UIColor(hex: "#b0c4de")
          public static let lightyellow = UIColor(hex: "#ffffe0")
          public static let lime = UIColor(hex: "#00ff00")
          public static let limegreen = UIColor(hex: "#32cd32")
          public static let linen = UIColor(hex: "#faf0e6")
          public static let magenta = UIColor(hex: "#ff00ff")
          public static let maroon = UIColor(hex: "#800000")
          public static let mediumaquamarine = UIColor(hex: "#66cdaa")
          public static let mediumblue = UIColor(hex: "#0000cd")
          public static let mediumorchid = UIColor(hex: "#ba55d3")
          public static let mediumpurple = UIColor(hex: "#9370db")
          public static let mediumseagreen = UIColor(hex: "#3cb371")
          public static let mediumslateblue = UIColor(hex: "#7b68ee")
          public static let mediumspringgreen = UIColor(hex: "#00fa9a")
          public static let mediumturquoise = UIColor(hex: "#48d1cc")
          public static let mediumvioletred = UIColor(hex: "#c71585")
          public static let midnightblue = UIColor(hex: "#191970")
          public static let mintcream = UIColor(hex: "#f5fffa")
          public static let mistyrose = UIColor(hex: "#ffe4e1")
          public static let moccasin = UIColor(hex: "#ffe4b5")
          public static let navajowhite = UIColor(hex: "#ffdead")
          public static let navy = UIColor(hex: "#000080")
          public static let oldlace = UIColor(hex: "#fdf5e6")
          public static let olive = UIColor(hex: "#808000")
          public static let olivedrab = UIColor(hex: "#6b8e23")
          public static let orange = UIColor(hex: "#ffa500")
          public static let orangered = UIColor(hex: "#ff4500")
          public static let orchid = UIColor(hex: "#da70d6")
          public static let palegoldenrod = UIColor(hex: "#eee8aa")
          public static let palegreen = UIColor(hex: "#98fb98")
          public static let paleturquoise = UIColor(hex: "#afeeee")
          public static let palevioletred = UIColor(hex: "#db7093")
          public static let papayawhip = UIColor(hex: "#ffefd5")
          public static let peachpuff = UIColor(hex: "#ffdab9")
          public static let peru = UIColor(hex: "#cd853f")
          public static let pink = UIColor(hex: "#ffc0cb")
          public static let plum = UIColor(hex: "#dda0dd")
          public static let powderblue = UIColor(hex: "#b0e0e6")
          public static let purple = UIColor(hex: "#800080")
          public static let rebeccapurple = UIColor(hex: "#663399")
          public static let red = UIColor(hex: "#ff0000")
          public static let rosybrown = UIColor(hex: "#bc8f8f")
          public static let royalblue = UIColor(hex: "#4169e1")
          public static let saddlebrown = UIColor(hex: "#8b4513")
          public static let salmon = UIColor(hex: "#fa8072")
          public static let sandybrown = UIColor(hex: "#f4a460")
          public static let seagreen = UIColor(hex: "#2e8b57")
          public static let seashell = UIColor(hex: "#fff5ee")
          public static let sienna = UIColor(hex: "#a0522d")
          public static let silver = UIColor(hex: "#c0c0c0")
          public static let skyblue = UIColor(hex: "#87ceeb")
          public static let slateblue = UIColor(hex: "#6a5acd")
          public static let slategray = UIColor(hex: "#708090")
          public static let slategrey = UIColor(hex: "#708090")
          public static let snow = UIColor(hex: "#fffafa")
          public static let springgreen = UIColor(hex: "#00ff7f")
          public static let steelblue = UIColor(hex: "#4682b4")
          public static let tan = UIColor(hex: "#d2b48c")
          public static let teal = UIColor(hex: "#008080")
          public static let thistle = UIColor(hex: "#d8bfd8")
          public static let tomato = UIColor(hex: "#ff6347")
          public static let turquoise = UIColor(hex: "#40e0d0")
          public static let violet = UIColor(hex: "#ee82ee")
          public static let wheat = UIColor(hex: "#f5deb3")
          public static let white = UIColor(hex: "#ffffff")
          public static let whitesmoke = UIColor(hex: "#f5f5f5")
          public static let yellow = UIColor(hex: "#ffff00")
          public static let yellowgreen = UIColor(hex: "#9acd32")
    }
}
#endif
